owner: Lastorder-DC
repo: splat00n_ink

sites:
  - name: Splat00n.Ink Main
    url: https://splat00n.ink/about
  - name: Splat00n.Ink API
    url: https://splat00n.ink/api/v2/instance
    __dangerous__body_down_if_text_missing: '"version"'
  - name: Splat00n.Ink Streaming
    url: https://splat00n.ink/api/v1/streaming/health
    __dangerous__body_down_if_text_missing: 'OK'
  - name: Splat00n.Ink User
    url: https://splat00n.ink/api/v1/accounts/lookup?acct=admin
    __dangerous__body_down_if_text_missing: '110212030595971207'
  - name: Splat00n.Ink ActivityPub
    url: https://splat00n.ink/.well-known/webfinger?resource=acct:support@maratang.life
    __dangerous__body_down_if_text_missing: 'application/activity+json'
  - name: Splat00n.Ink Storage
    url: https://r2.maratang.life/check.txt
    icon: https://splat00n.ink/favicon.ico
    __dangerous__body_down_if_text_missing: 'OK'

status-website:
  cname: status.splat00n.ink
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Splat00n.Ink 서버 상태
  introTitle: "Splat00n.Ink 서버 상태"
  introMessage: Splat00n.Ink 서버 상태를 실시간으로 확인하실 수 있습니다.
  navbar:
    - title: 상태 페이지
      href: /
    - title: Splat00n.Ink
      href: https://splat00n.ink/

robotsText: "User-agent: * \n Disallow: /"
user-agent: Splat00nInk-Uptime-Checker/1.0.230417.0
i18n:
  activeIncidents: 진행중인 장애
  allSystemsOperational: 모든 시스템 정상
  incidentReport: "사고 번호 #$NUMBER 보고서 →"
  activeIncidentSummary: "발생일: $DATE / 댓글 $POSTS 개"
  incidentTitle: 사고 번호 $NUMBER 상세
  incidentDetails: 사고 상세
  incidentFixed: 해결됨
  incidentOngoing: 처리중
  incidentOpenedAt: "발생일: "
  incidentClosedAt: "처리일: "
  incidentViewOnGitHub: Github에서 확인하기
  incidentCommentSummary: "작성일: $DATE / 작성자: $AUTHOR"
  incidentBack: ← 사고 목록으로 돌아가기
  pastIncidents: 과거 사고
  pastIncidentsResolved: $MINUTES 분만에 해결됨 / 댓글 $POSTS 개
  liveStatus: 실시간 상태
  overallUptime: "전체 업타임: $UPTIME"
  overallUptimeTitle: 전체 업타임
  averageResponseTime: "평균 응답 속도: $TIMEms"
  averageResponseTimeTitle: 응답 속도
  sevelDayResponseTime: 일주일 응답 속도
  responseTimeMs: 응답 속도 (ms)
  up: 정상
  down: 다운됨
  degraded: 성능 저하
  ms: ms
  loading: 로딩중
  navGitHub: GitHub
  footer: 이 페이지는 [오픈 소스]($REPO)이며 [Upptime](https://upptime.js.org)으로 구동됩니다
  errorTitle: 오류 발생
  errorIntro: 최신 서버 상태를 가져오는 중 오류가 발생했습니다.
  errorText: 잠시 후 다시 시도해 주세요.
  errorHome: 메인 페이지로 이동
  pastScheduledMaintenance: 지난 계획된 유지보수
  scheduledMaintenance: 계획된 유지보수
  scheduledMaintenanceSummaryStarted: "시작됨: $DATE / $DURATION 분동안 진행 예정"
  scheduledMaintenanceSummaryStarts: "시작 예정: $DATE / $DURATION 분동안 진행 예정"
  startedAt: "시작됨: "
  startsAt: "시작 예정: "
  duration: "진행 예정: "
  durationMin: "$DURATION 분"
  incidentCompleted: 완료됨
  incidentScheduled: 계획됨
